version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --tag registry.heroku.com/fstweet-jt/web .
      - deploy:
        name: Push application Docker image
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS registry.heroku.com
            docker push registry.heroku.com/fstweet-jt/web
          fi      
