version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build .
      # TODO: run tests!
  deploy-job:
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Deploy master to Heroku
          command: |
            heroku container:login
            heroku container:push web --app $HEROKU_APP_NAME
            heroku container:release web --app $HEROKU_APP_NAME
               
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
