version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build .
  deploy-job:
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      # - add_ssh_keys:
      #     fingerprints:
      #       - "87:da:92:b5:bf:18:cd:06:58:25:64:de:2b:cf:93:b3"
      - run:
          name: Deploy master to Heroku
          command: |
            heroku container:push web
            heroku container:release web
               
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
